#import "style.typ": *

#pagebreak(weak: true)
// #v(-1em)
#[#show heading: none
  #heading(level: 1, outlined: true)[Vocabulary]
]
== Vocabulary
#[
  #let sa(t) = sanskrit(t)
  #let ro(t) = romanization(t)
  #import "vocab.typ"
  #import "vocab.typ": masculine, feminine, neuter
  #import "vocab.typ": adjective, indeclinable, pronoun, prefix, verb_prefix
  #let verb = vocab.verb.with(label: [])
  #let verb_prefix(prefix, rt, form) = [#romanization[#prefix] + #verb(rt, form)]

#vocab.list(
  row-gutter: 2.8em,
  [अग्नि:], masculine[agniḥ], [fire],
  [अति], prefix[ati], [across, beyond, surpassing],
  [अतिथिः], masculine[atithiḥ], [guest],
  [अतीव], indeclinable[atīva], [very],
  [अत्र], indeclinable[atra], [here],
  [अधि], prefix[adhi], [above, over, on],
  [अनु], prefix[anu], [after, following],
  [अप], prefix[apa], [away, off],
  [अपि], prefix[api], [on, close on],
  [अपि], indeclinable[api], [also, too],
  [अभि], prefix[abhi], [to, against],
  [अमृतम्], neuter[amṛtam], [immortality],
  [अल्प], adjective[alpa][ā], [little],
  [अव], prefix[ava], [down, away, off],
  [अव~गम्], verb_prefix[ava][gam][avagacchati], [he understands],
  [अविद्या], feminine[avidyā], [ignorance],
  [अश्वः], masculine[aśvaḥ], [horse],
  [अष्त], vocab.generic[aṣṭa], [eight],
  [अष्टम], adjective[aṣṭama][ī], [eighth],
  [अस्], verb[as][asti], [he, she, it is],
  [असिद्धिः], feminine[asiddhiḥ], [failure],
  [अस्मद्], pronoun[asmad], [we (used in compounds)],
  [अहो], indeclinable[aho], [aha, hey!],
  [आ], prefix[ā], [back, return],
  [आ~गम्], verb_prefix[ā][gam][āgacchati], [he comes],
  [आ~नी], verb_prefix[ā][nī][ānayati], [he brings],
  [आचार्यः], masculine[ācāryaḥ], [teacher],
  [आत्मन्], masculine[ātman], [Self],
  [इति], indeclinable[iti], [(end of quote)],
  [इव], indeclinable[iva], [as if, like],
  [उद् भू], verb_prefix[ud][bhū][udbhavati], [he is born],
  [उद्~स्था], verb_prefix[ud][sthā][uttiṣṭhati], [he stands up],
  [उप], prefix[upa], [near, towards],
  [उप~गम्], verb_prefix[upa][gam][upagacchati], [he goes towards, he approaches],
  [ऋषिः], masculine[ṛṣiḥ], [seer],
  [एक], vocab.generic[eka], [one],
  [एव], indeclinable[eva], [only, ever#sidenote[indeed]],
  [एवम्], indeclinable[evam], [this, in this way],
  [कथम्], indeclinable[katham], [how],
  [कथा], feminine[kathā], [story],
  [कदा], indeclinable[kadā], [when],
  [कन्या], feminine[kanyā], [girl],
  [कर्तृ], masculine[kartṛ], [maker, doer],
  [कर्मन्], neuter[karman], [action],
  [कविः], masculine[kaviḥ], [poet],
  [कुत्र], indeclinable[kutra], [where],
  [कुपित], adjective[kupita][ā], [angry],
  [कुलम्], neuter[kulam], [family],
  [कीर्तिः], feminine[kīrtiḥ], [glory, fame],
  [कृष्ण], adjective[kṛṣṇa][ā], [black],
  [कृष्णः], masculine[kṛṣṇaḥ], [Kṛṣṇa],
  [गजः], masculine[gajaḥ], [elephant],
  [गम्], verb[gam][gacchati], [he goes],
  [गुप], verb[gup][gopāyati], [he protects],
  [गुरु], adjective[guru][vī], [heavy],
  [गुरुः], masculine[guruḥ], [teacher],
  [गृहम्], neuter[gṛham], [house],
  [ग्रामः], masculine[grāmaḥ], [village],
  [च], indeclinable[ca], [and],
  [चतुर्], vocab.generic[catur], [four],
  [चतुर्थ], adjective[caturtha][ī], [fourth],
  [चन्द्रः], masculine[candraḥ], [moon],
  [चिन्त्], verb[cint][cintayati -te], [he thinks],
  [छाया], feminine[chāyā], [shadow],
  [जलम्], neuter[jalam], [water],
  [जि], verb[ji][jayati], [he conquers],
  [ज्ञानम्], neuter[jñānam], [knowledge],
  [ततः], indeclinable[tataḥ], [therefore],
  [तत्र], indeclinable[tatra], [there],
  [तथा], indeclinable[tathā], [so, therefore],
  [तद्], pronoun[tad], [he, she, it],
  [तदा], indeclinable[tadā], [then],
  [तुरीय], adjective[turīya][ā], [fourth],
  [तृतीय], adjective[tṛtīya][ā], [third],
  [त्वद्], pronoun[tvad], [you (used in compounds)],
  [त्रि], vocab.generic[tri], [three],
  [दश], vocab.generic[daśa], [ten],
  [दशम], adjective[daśama][ī], [tenth],
  [दातृ], masculine[dātṛ], [giver],
  [दात्री], feminine[dātrī], [giver],
  [दुस्], prefix[dus], [ill, bad, difficult, hard],
  [दुःखम्], neuter[duḥkham], [suffering],
  [दृश्], verb[dṛś][paśyati], [he sees],
  [द्वि], vocab.generic[dvi], [two],
  [द्वितीय], adjective[dvitīya][ā], [second],
  [धार्मिक], adjective[dhārmika][ā], [virtuous],
  [धेनुः], feminine[dhenuḥ], [cow],
  [न], indeclinable[na], [not],
  [नदी], feminine[nadī], [river],
  [नरः], masculine[naraḥ], [man],
  [नव], vocab.generic[nava], [nine],
  [नवम], adjective[navama][ī], [ninth],
  [नाम], indeclinable[nāma], [by name],
  [नामन्], neuter[nāman], [name],
  [नि], prefix[ni], [down, into],
  [निस्], prefix[nis], [out, forth, without, entirely],
  [नी], verb[nī][nayati -te], [he leads],
  [नृपः], masculine[nṛpaḥ], [king],
  [पञ्च], vocab.generic[pañca], [five],
  [पञचम], adjective[pañcama][ī], [fifth],
  [पठ्], verb[paṭh][paṭhati], [he reads],
  [पत्नी], feminine[patnī], [wife],
  [परा], prefix[parā], [away, forth],
  [परि], prefix[pari], [around, about],
  [पश्], verb[paś][paśyati], [he sees],
  [पा], verb[pā][pibati], [he drinks],
  [पितृ], masculine[pitṛ], [father],
  [पुत्रः], masculine[putraḥ], [son],
  [पुत्रिका], feminine[putrikā], [daughter],
  [पुनर्], indeclinable[punar], [again],
  [पुस्तकम्], neuter[pustakam], [book],
  [पूर्ण], adjective[pūrṇa][ā], [full],
  [प्र], prefix[pra], [forward, onward],
  [प्रछ्], verb[prach][pṛcchati], [he asks],
  [प्रजा], feminine[prajā], [child, subject (of a king)],
  [प्रति], prefix[prati], [back to, in reverse direction, every],
  [प्रति~गम्], verb_prefix[prati][gam][pratigacchati], [he goes back, he returns],
  [प्रथम], adjective[prathama][ā], [first],
  [प्रिय], adjective[priya][ā], [dear, beloved],
  [फलम्], neuter[phalam], [fruit],
  [बहु], adjective(alt: [u])[bahu][vī], [much, many],
  [बालः], masculine[bālaḥ], [boy],
  [बाला], feminine[bālā], [girl],
  [बुध्], verb[budh][bodhati -te], [he knows],
  [भार्या], feminine[bhāryā], [wife],
  [भाष्], verb[bhāṣ][bhāṣate], [he speaks],
  [भीत], adjective[bhīta][ā], [afraid],
  [भू], verb[bhū][bhavati], [he is],
  [भूमिः], feminine[bhūmiḥ], [earth],
  [भ्रातृ], masculine[bhrātṛ], [brother],
  [मद्], pronoun[mad], [I (used in compounds)],
  [मन्], verb[man][manyate], [he thinks],
  [मातृ], feminine[mātṛ], [mother],
  [माला], feminine[mālā], [garland],
  [मित्रम्], neuter[mitram], [friend],
  [मृगः], masculine[mṛgaḥ], [deer],
  [यतः], indeclinable[yataḥ], [since],
  [यत्र], indeclinable[yatra], [where],
  [यथा], indeclinable[yathā], [since],
  [यद्], pronoun(label: [rel. pro.])[yad], [who, what, which (declined like #ro[tad])],
  [यदा], indeclinable[yadā], [when],
  [यदि], indeclinable[yadi], [if],
  [युष्मद्], pronoun[yuṣmad], [you (used in compounds)],
  [रम्], verb[ram][ramate], [he enjoys],
  [रमणीय], adjective[ramaṇīya][ā], [pleasant],
  [राजन्], masculine[rājan], [king],
  [रामः], masculine[rāmaḥ], [Rāma],
  [लभ्], verb[labh][labhate], [he obtains],
  [वद्], verb[vad][vadati], [he speaks],
  [वनम्], neuter[vanam], [forest],
  [वस्], verb[vas][vasati], [he lives],
  [वा], indeclinable[vā], [or],
  [वापी], feminine[vāpī], [pond],
  [वि], prefix[vi], [apart, away, out],
  [विद्या], feminine[vidyā], [knowledge],
  [विना], indeclinable[vinā], [without],
  [वीरः], masculine[vīraḥ], [hero],
  [शत्रुः], masculine[śatruḥ], [enemy],
  [शान्तिः], feminine[śāntiḥ], [peace],
  [शास्त्रम्], neuter[śāstram], [scripture],
  [शिष्यः], masculine[śiṣyaḥ], [student],
  [शीघ्र], adjective[śīghra][ā], [swift],
  [शुक्ल], adjective[śukla][ā], [white],
  [शुभ्], verb[śubh][śobhate], [he shines],
  [शोभन], adjective(alt: [ī])[śobhana][ā], [shining, bright, beautiful],
  [षष्], vocab.generic[ṣaṣ], [six],
  [षष्ठ], adjective[ṣaṣṭha][ī], [sixth],
  [सत्यम्], neuter[satyam], [truth],
  [सप्त], vocab.generic[sapta], [seven],
  [सप्तम], adjective[saptama][ī], [seventh],
  [साम्], prefix[sam], [together],
  [सह], indeclinable[saha], [with],
  [सिद्धः], [#vocab.generic[siddhaḥ] mf(#romanization[siddhā])], [one who attains perfection],
  [सिद्धिः], feminine[siddhiḥ], [perfection, attainment, proof],
  [सीता], feminine[sītā], [Sītā],
  [सु], prefix[su], [well, very good, right, easy],
  [सुखम्], neuter[sukham], [happiness],
  [सुन्दर], adjective[sundara][ī], [beautiful],
  [सूक्तम्], neuter[sūktam], [hymn],
  [सूर्यः], masculine[sūryaḥ], [sun],
  [सेना], feminine[senā], [army],
  [सेव्], verb[sev][sevate], [he serves],
  [स्था], verb[sthā][tiṣṭhati], [he stands],
  [स्मि], verb[smi][smayate], [he smiles],
  [स्मृ], verb[smṛ][smarati], [he remembers],
  [स्वसृ], feminine[svasṛ], [sister],
  [हस्], verb[has][hasati], [he laughs],
  [हस्तः], masculine[hastaḥ], [hand],
  [हेतुः], masculine[hetuḥ], [cause, motive]
)
]


#pagebreak(weak: true)

#[#show heading: none
  #heading(level: 1, outlined: true)[English-Sanskrit Vocabulary]
]
== English-Sanskrit Vocabulary
#[
  #let sa(t) = sanskrit(t)
  #let ro(t) = romanization(t)

  #import "vocab.typ"
  #import "vocab.typ": masculine, feminine, neuter
  #import "vocab.typ": adjective, indeclinable, pronoun, prefix, verb_prefix
  #let verb = vocab.verb.with(label: [])
  #let verb_prefix(prefix, rt, form) = [#romanization[#prefix] + #verb(rt, form)]
  #set par(leading: .6em)

#table(
  columns: 3, //(2fr, 1fr, 2fr),
  column-gutter: 0.5em,
  row-gutter: 1.85em,

  [above, over, on], sa[अधि], prefix[adhi],
  [across, beyond, surpassing], sa[अति], prefix[ati],
  [action], sa[कर्मन्], neuter[karman],
  [afraid], sa[भीत], adjective[bhīta][ā],
  [after, following], sa[अनु], prefix[anu],
  [again], sa[पुनर्], indeclinable[punar],
  [aha, hey!], sa[अहो], indeclinable[aho],
  [also, too], sa[अपि], indeclinable[api],
  [and], sa[च], indeclinable[ca],
  [angry], sa[कुपिता], adjective[kuptā][ā],
  [apart, away, out], sa[वि], prefix[vi],
  [army], sa[सेना], feminine[senā],
  [around, about], sa[परि], prefix[pari],
  [as if, like], sa[इव], indeclinable[iva],
  [ask], sa[प्रछ्], verb[prach][pṛcchati],
  [away, forth], sa[परा], prefix[parā],
  [away, off], sa[अप], prefix[apa],
  [back, return, back to in reverse direction,], sa[आ], prefix[ā],
  [every], sa[प्रति], prefix[prati],
  [beautiful], sa[सुन्दर], adjective[sundara][ī],
  [black], sa[कृष्ण], adjective[kṛṣṇa][ā],
  [book], sa[पुस्तकम्], neuter[pustakam],
  [born], sa[उद् भू], verb_prefix([ud], [bhū], [udbhavati]),
  [boy], sa[बालः], masculine[bālaḥ],
  [bring], sa[आ नि], verb_prefix([ā], [nī], [ānayati]),
  [brother], sa[भ्रातृ], masculine[bhrātṛ],
  [by name, named], sa[नाम], indeclinable[nāma],
  [cause, motive], sa[हेतुः], masculine[hetuḥ],
  [child, subject (of a king)], sa[प्रजा], feminine[prajā],
  [come], sa[आ गम्], verb_prefix[ā][gam][āgacchati],
  [conquer], sa[जि], verb[ji][jayati],
  [cow], sa[धेनुः], feminine[dhenuḥ],
  [daughter], sa[पुत्रिका], feminine[putrikā],
  [dear, beloved], sa[प्रिय], adjective[priya][ā],
  [deer], sa[मृगः], masculine[mṛgaḥ],
  [doer], sa[कर्तृ], masculine[kartṛ],
  [down], sa[अव], prefix[ava],
  [down, into], sa[नि], prefix[ni],
  [drink], sa[पा], verb[pā][pibati],
  [earth], sa[भूमिः], feminine[bhūmiḥ],
  [eigth], sa[अष्ट], vocab.generic[aṣṭa],
  [eighth], sa[अष्टम], adjective[aṣṭama][ī],
  [elephant], sa[गजः], masculine[gajaḥ],
  [(end of quote)], sa[इति], indeclinable[iti],
  [enemy], sa[शत्रुः], masculine[śatruḥ],
  [enjoy], sa[रम्], verb[ram][ramate],
  [failure], sa[असिद्धिः], feminine[asiddhiḥ],
  [family], sa[कुलम्], neuter[kulam],
  [father], sa[पितृ], masculine[pitṛ],
  [fifth], sa[पञ्चम], adjective[pañcama][ī],
  [fire], sa[अग्निः], masculine[agniḥ],
  [first], sa[प्रथम], adjective[prathama][ā],
  [five], sa[पञ्च], vocab.generic[pañca],
  [forest], sa[वनम्], neuter[vanam],
  [forward, onward, forth], sa[प्र], prefix[pra],
  [four], sa[चतुर्], vocab.generic[catur],
  [fourth], sa[चतुर्थ], adjective[caturtha][ī],
  [fourth], sa[तुरीय], adjective[turīya][ā],
  [friend], sa[मित्रम्], neuter[mitram],
  [fruit], sa[फलम्], neuter[phalam],
  [full], sa[पूर्ण], adjective[pūrṇa][ā],
  [garland], sa[माला], feminine[mālā],
  [girl], sa[कन्या], feminine[kanyā],
  [girl], sa[बाला], feminine[bālā],
  [giver], sa[दातृ], masculine[dātṛ],
  [giver], sa[दातृी], feminine[dātṛī],
  [glory, fame], sa[कीर्तिः], feminine[kīrtiḥ],
  [go], sa[गम्], verb[gam][gacchati],
  [go back, return], sa[प्रति गम्], verb_prefix[prati][gam][pratigacchati],
  [go forward, approach], sa[उप गम्], verb_prefix[upa][gam][upagacchati],
  [guest], sa[अतिथिः], masculine[atithiḥ],
  [hand], sa[हस्तः], masculine[hastaḥ],
  [happiness], sa[सुखम्], neuter[sukham],
  [he (see declension)], sa[तद्], pronoun[tad],
  [heavy], sa[गुरु], adjective[guru][vī],
  [here], sa[अत्र], indeclinable[atra],
  [hero], sa[वीरः], masculine[vīraḥ],
  [horse], sa[अश्वः], masculine[aśvaḥ],
  [house], sa[गृहम्], neuter[gṛham],
  [how], sa[कथम्], indeclinable[katham],
  [hymn], sa[सूक्तम्], neuter[sūktam],
  [I (used in compounds)], sa[मद्], pronoun[mad],
  [if], sa[यदि], indeclinable[yadi],
  [ignorance], sa[अविद्या], feminine[avidyā],
  [ill, bad, difficult, hard], sa[दुस्], pronoun[dus],
  [immortality], sa[अमृतम्], neuter[amṛtam],
  [is], sa[अस्], verb[as][asti],
  [is], sa[भू], verb[bhū][bhavati],
  [it (used in compounds)], sa[तद्], pronoun[tad],
  [king], sa[नृपः], masculine[nṛpaḥ],
  [king], sa[राजन्], masculine[rājan],
  [know], sa[बुध्], verb[budh][bodhati -te],
  [knowledge], sa[ज्ञानम्], neuter[jñānam],
  [knowledge], sa[विद्या], feminine[vidyā],
  [Kṛṣṇa], sa[कृष्णः], masculine[kṛṣṇaḥ],
  [laugh], sa[हस्], verb[has][hasati],
  [lead], sa[नी], verb[nī][nayati -te],
  [little], sa[अल्प], adjective[alpa][ā],
  [live], sa[वसति], verb[vas][vasati],
  [maker], sa[कर्तृ], masculine[kartṛ],
  [man], sa[नरः], masculine[naraḥ],
  [moon], sa[चन्द्रः], masculine[candraḥ],
  [mother], sa[मातृ], feminine[mātṛ],
  [much, many], sa[बहुः], adjective(alt: [u])[bahuḥ][vī],
  [name], sa[नामन्], neuter[nāman],
  [nine], sa[नव], vocab.generic[nava],
  [ninth], sa[नवम], adjective[navam][ī],
  [not], sa[न], indeclinable[na],
  [obtain], sa[लभ्], verb[labh][labhate],
  [on, close on], sa[अपि], prefix[api],
  [one], sa[एक], vocab.generic[eka],
  [one who attains perfection], sa[सिद्धः], masculine[siddhaḥ],
  [one who attains perfection], sa[सिद्धा], feminine[siddhā],
  [only, ever (emphativ)], sa[एव], indeclinable[eva],
  [or], sa[वा], indeclinable[vā],
  [out, forth], sa[निस्], prefix[nis],
  [peace], sa[शान्तिः], feminine[śantiḥ],
  [perfection, attainment, proof], sa[सिद्धिः], feminine[siddhiḥ],
  [pleasant], sa[रमणीय], adjective[ramaṇīya][ā],
  [poet], sa[कविः], masculine[kaviḥ],
  [pond], sa[वापी], feminine[vāpī],
  [protect], sa[गुप्], verb[gup][gopāyati],
  [Rāma], sa[रामः], masculine[rāmaḥ],
  [read], sa[पठ्], verb[paṭh][paṭhati],
  [remember], sa[स्मृ], verb[smṛ][smarati],
  [river], sa[नदी], feminine[nadī],
  [scripture, text], sa[शास्त्रम्], neuter[śāstram],
  [second], sa[द्वितीय], adjective[dvitīya][ā],
  [see], sa[दृश्], verb[dṛś][paśyati],
  [see], sa[पश्], verb[paś][paśyati],
  [seer, sage], sa[ऋषिः], masculine[ṛṣiḥ],
  [Self], sa[आत्मन्], masculine[ātman],
  [serve], sa[सेव्], verb[sev][sevate],
  [seven], sa[सप्त], vocab.generic[seven],
  [seventh], sa[सप्तम], adjective[saptama][ī],
  [shadow], sa[छाया], feminine[chāyā],
  [she (see declension)], sa[तद्], pronoun[tad],
  [shine], sa[शुभ], verb[śubh][śobhate],
  [shining, bright, beautiful], sa[शोभन], adjective(alt: [ī])[śobhana][ā],
  [since], sa[यतः], indeclinable[yataḥ],
  [since], sa[यथा], indeclinable[yathā],
  [sister], sa[स्वसृ], feminine[svāsṛ],
  [Sītā], sa[सीता], feminine[sītā],
  [six], sa[षष्], vocab.generic[ṣaṣ],
  [sixth], sa[षष्ठ], adjective[ṣaṣṭha][ī],
  [smile], sa[स्मि], verb[smi][smayate],
  [so, therefore], sa[तथा], indeclinable[tathā],
  [son], sa[पुत्रः], masculine[putraḥ],
  [speak], sa[भाष्], verb[bhāṣ][bhāṣate],
  [speak], sa[वद्], verb[vad][vadati],
  [stand], sa[स्था], verb[sthā][tiṣṭhati],
  [stand up], sa[उत् स्था], verb_prefix[ut][sthā][uttiṣṭhati],
  [story], sa[कथा], feminine[kathā],
  [student], sa[शिष्यः], masculine[śiṣyaḥ],
  [subject (of a king)], sa[प्रजा], feminine[prajā],
  [suffering], sa[दुःखम्], neuter[duḥkham],
  [sun], sa[सूर्यः], masculine[sūryaḥ],
  [swift], sa[शीघ्र], adjective[śīghra][ā],
  [teacher], sa[आचार्यः], masculine[ācāryaḥ],
  [teacher], sa[गुरुः], masculine[guruḥ],
  [ten], sa[दश], vocab.generic[daśa],
  [tenth], sa[दशम], adjective[daśama][ī],
  [then], sa[तदा], indeclinable[tadā],
  [there], sa[तत्र], indeclinable[tatra],
  [therefore], sa[ततः], indeclinable[tataḥ],
  [think], sa[चिन्त्], verb[cint][cintayati -te],
  [think], sa[मन्], verb[man][manyate],
  [third], sa[तृतीय], adjective[tṛtīya][ā],
  [three], sa[त्रि], vocab.generic[tri],
  [thus, in this way], sa[एवम्], indeclinable[evam],
  [to, against], sa[अभि], prefix[abhi],
  [together], sa[सम्], prefix[sam],
  [towards], sa[उप], prefix[upa],
  [truth], sa[सत्यम्], neuter[satyam],
  [two], sa[द्वि], vocab.generic[dvi],
  [understand], sa[अव गम्], verb_prefix[ava][gam][avagacchati],
  [up, up out], sa[उद्], prefix[ud],
  [very], sa[अतीव], indeclinable[atīva],
  [village], sa[ग्रामः], masculine[grāmaḥ],
  [virtuous], sa[धार्मिक], adjective[dharmika][ī],
  [water], sa[जलम्], neuter[jalam],
  [we (used in compounds)], sa[अस्मद्], pronoun[asmad],
  [well, very, good, right, easy], sa[सु], prefix[su],
  [when (question)], sa[कदा], indeclinable[kadā],
  [when], sa[यदा], indeclinable[yadā],
  [where (question)], sa[कुत्र], indeclinable[kutra],
  [where], sa[यत्र], indeclinable[yatra],
  [white], sa[शुक्ल], adjective[śukla][ā],
  [who, what (declined like #romanization[tad])], sa[यद्], pronoun(label: [rel. pro.])[yad],
  [with], sa[सह], indeclinable[saha],
  [without], sa[विना], indeclinable[vinā],
  [wife], sa[पत्नी], feminine[patnī],
  [wife], sa[बार्या], feminine[bhāryā],
  [you (sing., used in compounds)], sa[त्वद्], pronoun[tvad],
  [you (plural, used in compounds)], sa[युष्मद्], pronoun[yuṣmad],
)
]
